package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// gitignore_coverage cross-references the project's .gitignore against a
// hardcoded "if you have X, you must ignore Y" table. Deterministic: the
// table is fixed, the .gitignore parsing is line-by-line, no heuristics.
//
// Patterns we expect are normalised so all the equivalent ways of writing
// them in .gitignore — `node_modules`, `node_modules/`, `/node_modules` —
// are treated as equivalent coverage.

type stackRequirement struct {
	// marker is a project file/dir whose presence triggers this rule.
	marker string
	// patterns are the .gitignore entries that must cover the bloat.
	patterns []string
	// reason is appended to the finding message.
	reason string
}

var stackRequirements = []stackRequirement{
	{
		marker:   "package.json",
		patterns: []string{"node_modules"},
		reason:   "Node projects rebuild node_modules from package.json + lockfile; committing it bloats the repo and breaks installs.",
	},
	{
		marker:   "Cargo.toml",
		patterns: []string{"target"},
		reason:   "Cargo's build artefacts live under target/; they're regenerated on every `cargo build`.",
	},
	{
		marker:   "pyproject.toml",
		patterns: []string{"__pycache__", ".venv"},
		reason:   "Python bytecode and virtualenv directories are user-local and should never travel through git.",
	},
	{
		marker:   "setup.py",
		patterns: []string{"__pycache__", ".venv"},
		reason:   "Python bytecode and virtualenv directories are user-local and should never travel through git.",
	},
	{
		marker:   "Gemfile",
		patterns: []string{".bundle", "vendor/bundle"},
		reason:   "Bundler caches and vendored gems shouldn't ship in source.",
	},
	{
		marker:   "go.mod",
		patterns: []string{}, // intentionally empty; vendored Go modules are opt-in
	},
}

// universalPatterns are added unconditionally — these are universally
// noise regardless of stack.
var universalPatterns = []string{
	".DS_Store",
}

// gitignoreCoverageOptions plumbs the standard exclude/disable knobs.
type gitignoreCoverageOptions struct {
	scanOptions
	DisabledPatterns []string `json:"disabled_patterns,omitempty"`
}

func checkGitignoreCoverage(_ context.Context, root string, opts json.RawMessage) ([]Finding, error) {
	options := parseGitignoreCoverageOptions(opts)
	disabled := map[string]bool{}
	for _, p := range options.DisabledPatterns {
		disabled[normaliseGitignorePattern(p)] = true
	}

	required := []stackRequirement{}
	// Apply universals only if we have *anything* tracked — otherwise
	// it's an empty repo where the noise hasn't materialised yet.
	if hasAnyMarker(root) {
		required = append(required, stackRequirement{
			marker:   "",
			patterns: universalPatterns,
			reason:   "Generated by macOS/Windows/IDEs; never relevant to the project.",
		})
	}
	for _, req := range stackRequirements {
		if req.marker == "" || len(req.patterns) == 0 {
			continue
		}
		if _, err := os.Stat(filepath.Join(root, req.marker)); err == nil {
			required = append(required, req)
		}
	}
	if len(required) == 0 {
		return nil, nil
	}

	// Read .gitignore (missing is its own gate — gitignore_present).
	covered, err := readGitignorePatterns(root)
	if err != nil {
		return nil, nil
	}

	out := []Finding{}
	for _, req := range required {
		for _, want := range req.patterns {
			normalised := normaliseGitignorePattern(want)
			if disabled[normalised] {
				continue
			}
			if covered[normalised] {
				continue
			}
			advice := req.reason
			if advice == "" {
				advice = "Add it to .gitignore."
			}
			out = append(out, Finding{
				Severity: SeverityWarning,
				Title:    fmt.Sprintf("Missing .gitignore entry: %s", want),
				Message: fmt.Sprintf(
					".gitignore does not cover `%s`. %s Add `%s` to your .gitignore.",
					want, advice, want,
				),
				FilePath: ".gitignore:" + want,
			})
		}
	}
	return out, nil
}

// hasAnyMarker returns true if any of the recognised stack markers exist
// at the project root. Used to gate the universal .DS_Store rule so we
// don't add noise to a fresh empty repo.
func hasAnyMarker(root string) bool {
	for _, req := range stackRequirements {
		if req.marker == "" {
			continue
		}
		if _, err := os.Stat(filepath.Join(root, req.marker)); err == nil {
			return true
		}
	}
	// Also accept anything we'd consider "a real source tree".
	for _, m := range []string{"go.mod", "Gemfile", "composer.json", "mix.exs", "pom.xml"} {
		if _, err := os.Stat(filepath.Join(root, m)); err == nil {
			return true
		}
	}
	return false
}

// readGitignorePatterns parses .gitignore at the project root and
// returns the set of normalised patterns it covers. Negation lines (!) and
// directory-internal .gitignores are ignored — this gate is about the
// repo's top-level coverage.
func readGitignorePatterns(root string) (map[string]bool, error) {
	data, err := os.ReadFile(filepath.Join(root, ".gitignore"))
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(strings.TrimSuffix(raw, "\r"))
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}
		out[normaliseGitignorePattern(line)] = true
	}
	return out, nil
}

// normaliseGitignorePattern collapses `node_modules`, `node_modules/`,
// `/node_modules`, `/node_modules/` to the same canonical key. The .git
// matching rules treat them identically when the target is a directory at
// the project root, which is the only thing this gate cares about.
func normaliseGitignorePattern(p string) string {
	p = strings.TrimSpace(p)
	p = strings.TrimPrefix(p, "/")
	p = strings.TrimSuffix(p, "/")
	return p
}

func parseGitignoreCoverageOptions(opts json.RawMessage) gitignoreCoverageOptions {
	if len(opts) == 0 {
		return gitignoreCoverageOptions{}
	}
	var o gitignoreCoverageOptions
	_ = json.Unmarshal(opts, &o)
	return o
}
